export const RECEIVE_DATAPACKAGE = 'RECEIVE_DATAPACKAGE'
export const RECEIVE_RESOURCE = 'RECEIVE_RESOURCE'
export const FETCH_PACKAGES_SUCCESS = 'FETCH_PACKAGES_SUCCESS'
export const FETCH_PUB_DETAILS_SUCCESS = 'FETCH_PUB_DETAILS_SUCCESS'
